### ISSUE TITLE
FreeBSD10.3: clang 3.4.1: bi_funct.c: line 32: s/b  #include <sys/wait.h> 

### ISSUE THREAD

**Issue by ossbsd** [mikebrennan000/mawk-2#1]
/usr/include/sys/wait.h macros used in bi_funct.c:
line 666 WIFEXITED
line 667 WEXITSTATUS
line 670 WTERMSIG
while converting syscall returns to userland returns.
Once bi_funct.c munged, compiled fine:
./configure
./make (no errors)
./make check (all tests returned success)

Thanks for this, I have always admired your work/mawk.

Environment:
HW: supermicro mb / xeon quad cpu
OS: x86_64 FreeBSD 10.3 
Compiler: clang 3.4.1

**Comment by mikebrennan000** [comment]
I added  #include <sys/wait.h>   to bi_funct.c.
That change and a couple of trivial changes are now in mawk-1.9.9.5.tar.gz.

Thank you for your help.   I appreciate the feedback.
